
package view;

import DAO.*;
import java.sql.*;
import javax.swing.DefaultListModel;
import model.*;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Munezero
 */
public class Dashboard extends javax.swing.JFrame {
    DefaultListModel classes;
    LinkedList classList;
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        getUserDetail();
        fillClassesCombo();
        fillStatusCombo();
        punishExecuteBtn.setVisible(false);
        punishPrintBtn.setVisible(false);
    }
    
    public void getUserDetail(){
            StaffDAO st = new StaffDAO();
            Staff s = st.getStaffById();
            msg.setText("Welcome Dear " + s.getFullNames());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        msg = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        permitIdBox = new javax.swing.JTextField();
        PermitSearchBtn = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        reasonBox1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        punishDaysBox1 = new javax.swing.JTextField();
        pStatusBox1 = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        punishPrintBtn1 = new javax.swing.JButton();
        punishExecuteBtn1 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        RemovePermissin = new javax.swing.JButton();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        reasonBox = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        punishDaysBox = new javax.swing.JTextField();
        pStatusBox = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        punishPrintBtn = new javax.swing.JButton();
        punishExecuteBtn = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        marksDeduBox = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        punishClassBtn = new javax.swing.JButton();
        classReasonBox = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        classMarksDeducted = new javax.swing.JTextField();
        punishClassCombo = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        pIdBox = new javax.swing.JTextField();
        punishSearchBtn = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        updatelabel = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        StudentForm = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        stIdBox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ClassBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        numberBox = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        marksBox = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        stNameBox = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        gNameBox = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        gEmailBox = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        statusBox = new javax.swing.JComboBox<>();
        marksBox1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        statusBox1 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        msg1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.textHighlight);

        msg.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        msg.setForeground(new java.awt.Color(51, 0, 153));
        msg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msg.setAlignmentX(1.0F);
        msg.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jTabbedPane3.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));

        jLabel23.setBackground(new java.awt.Color(51, 0, 153));
        jLabel23.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel23.setText("Enter the Id of the student to Give a permission");

        permitIdBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                permitIdBoxActionPerformed(evt);
            }
        });

        PermitSearchBtn.setText("Search");
        PermitSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PermitSearchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(permitIdBox)
                        .addGap(18, 18, 18)
                        .addComponent(PermitSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(permitIdBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PermitSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));

        jPanel13.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel27.setBackground(new java.awt.Color(51, 0, 153));
        jLabel27.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel27.setText("Reason for permission");

        reasonBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reasonBox1ActionPerformed(evt);
            }
        });

        jLabel28.setBackground(new java.awt.Color(51, 0, 153));
        jLabel28.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel28.setText("Days of Permission");

        jLabel29.setBackground(new java.awt.Color(51, 0, 153));
        jLabel29.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("ENTER DETAILS FOR PUNISHMENT FOR STUDENT");
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        punishDaysBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                punishDaysBox1ActionPerformed(evt);
            }
        });

        jLabel30.setBackground(new java.awt.Color(51, 0, 153));
        jLabel30.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel30.setText("Status");

        punishPrintBtn1.setText("Print Permission");

        punishExecuteBtn1.setText("Execute");
        punishExecuteBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                punishExecuteBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
                    .addComponent(reasonBox1)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(punishExecuteBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(punishPrintBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pStatusBox1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(punishDaysBox1)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel30)
                            .addComponent(jLabel28))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reasonBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(punishDaysBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pStatusBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(punishExecuteBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(punishPrintBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel14.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel32.setBackground(new java.awt.Color(51, 0, 153));
        jLabel32.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("PERMITTED STUDENTS");
        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        RemovePermissin.setText("Execute");
        RemovePermissin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemovePermissinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(RemovePermissin, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RemovePermissin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(976, 976, 976)))
                .addGap(19, 19, 19))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
        );

        jTabbedPane3.addTab("tab1", jPanel10);

        jTabbedPane1.addTab("Permissions", jTabbedPane3);

        jTabbedPane4.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 14852));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));

        jPanel8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel17.setBackground(new java.awt.Color(51, 0, 153));
        jLabel17.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel17.setText("Reason for Punishment");

        reasonBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reasonBoxActionPerformed(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(51, 0, 153));
        jLabel16.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel16.setText("Days of punishment");

        jLabel21.setBackground(new java.awt.Color(51, 0, 153));
        jLabel21.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("ENTER DETAILS FOR PUNISHMENT FOR STUDENT");
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        punishDaysBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                punishDaysBoxActionPerformed(evt);
            }
        });

        jLabel22.setBackground(new java.awt.Color(51, 0, 153));
        jLabel22.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel22.setText("Status");

        punishPrintBtn.setText("Print Expllutions ");

        punishExecuteBtn.setText("Execute");
        punishExecuteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                punishExecuteBtnActionPerformed(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(51, 0, 153));
        jLabel18.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel18.setText("Marks Deducted");

        marksDeduBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marksDeduBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pStatusBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(punishDaysBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reasonBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(marksDeduBox, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addComponent(punishExecuteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(punishPrintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel22))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reasonBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(punishDaysBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(marksDeduBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pStatusBox, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(punishPrintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(punishExecuteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel26.setBackground(new java.awt.Color(51, 0, 153));
        jLabel26.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("CLASS PUNISHMENT");
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        punishClassBtn.setText("Execute");
        punishClassBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                punishClassBtnActionPerformed(evt);
            }
        });

        classReasonBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classReasonBoxActionPerformed(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(51, 0, 153));
        jLabel19.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel19.setText("Reason for Punishment");

        jLabel24.setBackground(new java.awt.Color(51, 0, 153));
        jLabel24.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel24.setText("Marks Deducted");

        classMarksDeducted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classMarksDeductedActionPerformed(evt);
            }
        });

        jLabel25.setBackground(new java.awt.Color(51, 0, 153));
        jLabel25.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel25.setText("Select class to punish");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel25))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGap(232, 232, 232)
                                .addComponent(punishClassBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 52, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(classMarksDeducted)
                            .addComponent(punishClassCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(classReasonBox)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel19))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(punishClassCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(classReasonBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(classMarksDeducted, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(punishClassBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));

        jLabel20.setBackground(new java.awt.Color(51, 0, 153));
        jLabel20.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel20.setText("Enter the Id of the Student you want to punish");

        pIdBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pIdBoxActionPerformed(evt);
            }
        });

        punishSearchBtn.setText("Search");
        punishSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                punishSearchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(pIdBox)
                        .addGap(18, 18, 18)
                        .addComponent(punishSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pIdBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(punishSearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Punisment", jPanel2);

        jTabbedPane1.addTab("Sunctions", jTabbedPane4);

        jTabbedPane2.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        updatelabel.setBackground(new java.awt.Color(255, 255, 255));

        addBtn.setText("Add Student");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        updateBtn.setText("Update Student");
        updateBtn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                updateBtnFocusGained(evt);
            }
        });
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete Student");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
        );

        StudentForm.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setBackground(new java.awt.Color(51, 0, 153));
        jLabel7.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel7.setText("Student Id");

        jLabel8.setBackground(new java.awt.Color(51, 0, 153));
        jLabel8.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel8.setText("Class");

        jLabel9.setBackground(new java.awt.Color(51, 0, 153));
        jLabel9.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel9.setText("Guardian Number");

        numberBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberBoxActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(51, 0, 153));
        jLabel11.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel11.setText("Displine Marks");

        marksBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marksBoxActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(51, 0, 153));
        jLabel2.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel2.setText("Student Names");

        jLabel6.setBackground(new java.awt.Color(51, 0, 153));
        jLabel6.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel6.setText("Guardian Names");

        gNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gNameBoxActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(51, 0, 153));
        jLabel10.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel10.setText("Guardian Email");

        gEmailBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gEmailBoxActionPerformed(evt);
            }
        });

        jLabel12.setBackground(new java.awt.Color(51, 0, 153));
        jLabel12.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel12.setText("Status");

        marksBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marksBox1ActionPerformed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(51, 0, 153));
        jLabel13.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel13.setText("Data of Birth");

        statusBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));

        jLabel14.setBackground(new java.awt.Color(51, 0, 153));
        jLabel14.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel14.setText("Gender");

        javax.swing.GroupLayout StudentFormLayout = new javax.swing.GroupLayout(StudentForm);
        StudentForm.setLayout(StudentFormLayout);
        StudentFormLayout.setHorizontalGroup(
            StudentFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StudentFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentFormLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentFormLayout.createSequentialGroup()
                        .addGroup(StudentFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(marksBox1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(marksBox, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numberBox, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ClassBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stIdBox, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, StudentFormLayout.createSequentialGroup()
                                .addGroup(StudentFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(166, 166, 166)))
                .addGroup(StudentFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StudentFormLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentFormLayout.createSequentialGroup()
                        .addGroup(StudentFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(statusBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stNameBox, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gNameBox, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gEmailBox, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, StudentFormLayout.createSequentialGroup()
                                .addGroup(StudentFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(105, 105, 105))))
        );
        StudentFormLayout.setVerticalGroup(
            StudentFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StudentFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(StudentFormLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(8, 8, 8)
                        .addComponent(stNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(StudentFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(StudentFormLayout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gEmailBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statusBox, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(StudentFormLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(StudentFormLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stIdBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClassBox, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numberBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marksBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(StudentFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentFormLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(marksBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentFormLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout updatelabelLayout = new javax.swing.GroupLayout(updatelabel);
        updatelabel.setLayout(updatelabelLayout);
        updatelabelLayout.setHorizontalGroup(
            updatelabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(updatelabelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updatelabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updatelabelLayout.createSequentialGroup()
                        .addComponent(StudentForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(updatelabelLayout.createSequentialGroup()
                        .addGap(331, 331, 331)
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(updatelabelLayout.createSequentialGroup()
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(updateBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                        .addGap(165, 165, 165)
                        .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                        .addGap(113, 113, 113)
                        .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE))))
        );
        updatelabelLayout.setVerticalGroup(
            updatelabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updatelabelLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StudentForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(updatelabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(143, 143, 143))
        );

        jTabbedPane2.addTab("tab1", updatelabel);

        jTabbedPane1.addTab("Student", jTabbedPane2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1141, Short.MAX_VALUE)
        );

        msg1.setFont(new java.awt.Font("Unispace", 1, 36)); // NOI18N
        msg1.setForeground(new java.awt.Color(0, 0, 153));
        msg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msg1.setText("DISPLINE MANAGEMENT SYSTEM");
        msg1.setAlignmentX(1.0F);
        msg1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(522, 522, 522))))
            .addGroup(layout.createSequentialGroup()
                .addGap(431, 431, 431)
                .addComponent(msg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(281, 281, 281))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(msg1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gNameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gNameBoxActionPerformed

    private void numberBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberBoxActionPerformed

    private void gEmailBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gEmailBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gEmailBoxActionPerformed

    private void marksBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marksBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marksBoxActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        
        if(stIdBox.getText().trim().length() != 5){
            JOptionPane.showMessageDialog(this, "Student Id must be of 5 charcter long");
        }
        
        if (stNameBox.getText().trim().isEmpty() || gNameBox.getText().trim().isEmpty() ) {
            JOptionPane.showMessageDialog(this, "Student names, Guardian names and phone, email are required");
        }
        
        if (stNameBox.getText().trim().isEmpty() || gNameBox.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Student names, Guardian names and phone, email are required");
        }
        
        if (numberBox.getText().trim().length() != 10 || !numberBox.getText().startsWith("0") ) {
            JOptionPane.showMessageDialog(this, "Student Id must be of 5 charcter long");
        }
        
        Student student = new Student(stIdBox.getText(), stNameBox.getText(), ClassBox.getSelectedIndex()+1, gNameBox.getText(), numberBox.getText(), gEmailBox.getText(), Integer.parseInt(marksBox.getText()), statusBox.getSelectedIndex()+1);
        StudentDAO st = new StudentDAO();
        
        int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to add this student "+stNameBox.getText()+" with id "+stIdBox.getText(), "Confirmation", JOptionPane.YES_NO_OPTION);
        String feedback ="";
        if(result == JOptionPane.YES_OPTION){
            feedback = st.createStudent(student);
        }
        
        JOptionPane.showMessageDialog(this, feedback);
    }//GEN-LAST:event_addBtnActionPerformed

    private void updateBtnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_updateBtnFocusGained
        updatelabel.setToolTipText("To update Student details enter the id in the Id box abover\n Click the search button");
    }//GEN-LAST:event_updateBtnFocusGained

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        if (stIdBox.getText().trim().length() != 5) {
            JOptionPane.showMessageDialog(this, "Student Id must be of 5 charcter long");
        }

        if (stNameBox.getText().trim().isEmpty() || gNameBox.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Student names, Guardian names and phone, email are required");
        }

        if (stNameBox.getText().trim().isEmpty() || gNameBox.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Student names, Guardian names and phone, email are required");
        }

        if (numberBox.getText().trim().length() != 10 || !numberBox.getText().startsWith("0")) {
            JOptionPane.showMessageDialog(this, "Student Id must be of 5 charcter long");
        }

        Student student = new Student(stIdBox.getText(), stNameBox.getText(), ClassBox.getSelectedIndex() + 1, gNameBox.getText(), numberBox.getText(), gEmailBox.getText(), Integer.parseInt(marksBox.getText()), statusBox.getSelectedIndex() + 1);
        StudentDAO st = new StudentDAO();

        int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to update" + stNameBox.getText() + "'s Details?" + stIdBox.getText(), "Confirmation", JOptionPane.YES_NO_OPTION);
        String feedback = "";
        if (result == JOptionPane.YES_OPTION) {
            feedback = st.updateStudent(student);
        }else{
            return;
        }
        JOptionPane.showMessageDialog(this, feedback);
    }//GEN-LAST:event_updateBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        StudentDAO std = new  StudentDAO();
        Student st = new Student();
        st.setStudentId(stIdBox.getText());
        st = std.getStudentById(st);
        if(st != null){
            stNameBox.setText(st.getStudentNames());
            gNameBox.setText(st.getGuardianNames());
            gEmailBox.setText(st.getGuardianEmail());
            marksBox.setText(st.getMarks().toString());
            numberBox.setText(st.getGuardinaNumber());
            ClassBox.setSelectedIndex(st.getStudentClass()-1);
            statusBox.setSelectedIndex(st.getStatus()-1);
        }else{
            JOptionPane.showMessageDialog(this, "Student not found", "Missing", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if (stIdBox.getText().trim().length() != 5) {
            JOptionPane.showMessageDialog(this, "Student Id must be of 5 charcter long");
        }

        if (stNameBox.getText().trim().isEmpty() || gNameBox.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Student names, Guardian names and phone, email are required");
        }

        if (stNameBox.getText().trim().isEmpty() || gNameBox.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Student names, Guardian names and phone, email are required");
        }

        if (numberBox.getText().trim().length() != 10 || !numberBox.getText().startsWith("0")) {
            JOptionPane.showMessageDialog(this, "Student Id must be of 5 charcter long");
        }

        Student student = new Student(stIdBox.getText(), stNameBox.getText(), ClassBox.getSelectedIndex() + 1, gNameBox.getText(), numberBox.getText(), gEmailBox.getText(), Integer.parseInt(marksBox.getText()), statusBox.getSelectedIndex() + 1);
        StudentDAO st = new StudentDAO();

        int result = JOptionPane.showConfirmDialog(this, "Are you sure you want to update" + stNameBox.getText() + "'s Details?" + stIdBox.getText(), "Confirmation", JOptionPane.YES_NO_OPTION);
        String feedback = "";
        if (result == JOptionPane.YES_OPTION) {
            feedback = st.deleteStudent(student);
        } else {
            return;
        }
        JOptionPane.showMessageDialog(this, feedback);
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void marksBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marksBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marksBox1ActionPerformed

    private void reasonBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reasonBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reasonBoxActionPerformed

    private void punishDaysBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_punishDaysBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_punishDaysBoxActionPerformed

    private void pIdBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pIdBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pIdBoxActionPerformed

    private void punishSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_punishSearchBtnActionPerformed
        
        StudentDAO std = new StudentDAO();
        Student st = new Student();
        st.setStudentId(pIdBox.getText());
        st = std.getStudentById(st);
        if (st != null) {
            JOptionPane.showMessageDialog(this, "Student found \n You can proceed with add punishment", "Found", JOptionPane.OK_OPTION);
            punishExecuteBtn.setVisible(true);
            punishPrintBtn.setVisible(true);
            pIdBox.setEditable(false);
        } else {
            JOptionPane.showMessageDialog(this, "Student not found", "Missing", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_punishSearchBtnActionPerformed

    private void punishExecuteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_punishExecuteBtnActionPerformed
        String feedback = "";
        try{
        Punishment punishment = new Punishment(pIdBox.getText().trim(), reasonBox.getText().trim(), Integer.parseInt(punishDaysBox.getText().trim()), Integer.parseInt(marksDeduBox.getText().trim()), SessionManagement.id, pStatusBox.getSelectedIndex()+1);
        PunishmentDAO pn = new PunishmentDAO();
        
        int result = JOptionPane.showConfirmDialog(this, "Are you sure you want execute this?", "Confirmation", JOptionPane.YES_NO_OPTION);
        
        if (result == JOptionPane.YES_OPTION) {
            feedback = feedback = pn.AddStudentPunishment(punishment);
            // Reduce Student marks and  update the status
            Student std = new Student();
            std.setStudentId(pIdBox.getText());
            StudentDAO Stdao = new StudentDAO();
            Student Holder = new Student();
            Holder = Stdao.getStudentById(std);
            if(Holder != null){
                int newStudentMarks = Holder.getMarks() - Integer.parseInt(marksDeduBox.getText());
                std = new Student();
                std.setMarks(newStudentMarks);
                std.setStatus(pStatusBox.getSelectedIndex()+1);
                std.setStudentId(pIdBox.getText().trim());
                Stdao.updateStudentMarksAndStatus(std);
            }
            JOptionPane.showMessageDialog(this, feedback);
            pIdBox.setEditable(true);
        } else {
            return;
        } } catch(Exception e)   {
            e.printStackTrace();
            pIdBox.setEditable(true); 
        }    
    }//GEN-LAST:event_punishExecuteBtnActionPerformed

    private void marksDeduBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marksDeduBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marksDeduBoxActionPerformed

    private void classReasonBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classReasonBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classReasonBoxActionPerformed

    private void classMarksDeductedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classMarksDeductedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classMarksDeductedActionPerformed

    private void punishClassBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_punishClassBtnActionPerformed
        StudentDAO stda = new StudentDAO();
        Student std = new Student();
        std.setStudentClass(punishClassCombo.getSelectedIndex()+1);
        
       
        
    }//GEN-LAST:event_punishClassBtnActionPerformed

    private void permitIdBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_permitIdBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_permitIdBoxActionPerformed

    private void PermitSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PermitSearchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PermitSearchBtnActionPerformed

    private void reasonBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reasonBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reasonBox1ActionPerformed

    private void punishDaysBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_punishDaysBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_punishDaysBox1ActionPerformed

    private void punishExecuteBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_punishExecuteBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_punishExecuteBtn1ActionPerformed

    private void RemovePermissinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemovePermissinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemovePermissinActionPerformed

    public void fillClassesCombo(){
     
        ClassesDAO cl = new ClassesDAO();
        ResultSet rs = cl.getAvailableClasses();
        try{
            while (rs.next()) {
                ClassBox.addItem(rs.getString(2));
                punishClassCombo.addItem(rs.getString(2));
            }
        }catch(Exception e){
               e.printStackTrace();
        }
        
    }
    
    public void fillStatusCombo() {

        StatusDAO st = new StatusDAO();
        ResultSet rs = st.getStatuses();
        try {
            while (rs.next()) {
                statusBox.addItem(rs.getString(2));
                pStatusBox.addItem(rs.getString(2));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });

    // Variables declaration - do not modify                     
    // End of variables declaration                   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ClassBox;
    private javax.swing.JButton PermitSearchBtn;
    private javax.swing.JButton RemovePermissin;
    private javax.swing.JPanel StudentForm;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField classMarksDeducted;
    private javax.swing.JTextField classReasonBox;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField gEmailBox;
    private javax.swing.JTextField gNameBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextField marksBox;
    private javax.swing.JTextField marksBox1;
    private javax.swing.JTextField marksDeduBox;
    private javax.swing.JLabel msg;
    private javax.swing.JLabel msg1;
    private javax.swing.JTextField numberBox;
    private javax.swing.JTextField pIdBox;
    private javax.swing.JComboBox<String> pStatusBox;
    private javax.swing.JComboBox<String> pStatusBox1;
    private javax.swing.JTextField permitIdBox;
    private javax.swing.JButton punishClassBtn;
    private javax.swing.JComboBox<String> punishClassCombo;
    private javax.swing.JTextField punishDaysBox;
    private javax.swing.JTextField punishDaysBox1;
    private javax.swing.JButton punishExecuteBtn;
    private javax.swing.JButton punishExecuteBtn1;
    private javax.swing.JButton punishPrintBtn;
    private javax.swing.JButton punishPrintBtn1;
    private javax.swing.JButton punishSearchBtn;
    private javax.swing.JTextField reasonBox;
    private javax.swing.JTextField reasonBox1;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField stIdBox;
    private javax.swing.JTextField stNameBox;
    private javax.swing.JComboBox<String> statusBox;
    private javax.swing.JComboBox<String> statusBox1;
    private javax.swing.JButton updateBtn;
    private javax.swing.JPanel updatelabel;
    // End of variables declaration//GEN-END:variables
}